version: "3.8"

services:

    node:
        build:
            context: app/docker
            dockerfile: node/Dockerfile
        container_name: webpack-node
        volumes:
            - ./app:/app
        working_dir: /app

    node-up:
        build:
            context: app/docker
            dockerfile: node/Dockerfile
        container_name: webpack-node-up
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - 8080:8080
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run up"

    node-analizer:
        build:
            context: app/docker
            dockerfile: node/Dockerfile
        container_name: webpack-node-analizer
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - 8081:8081
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run analizer"